In [22]:

'''
Title -  Write a Python program to add a border (filled with 0's) around an existing array.
            Expected Output:
            Original array:
            [[ 1. 1. 1.]
            [ 1. 1. 1.]
            [ 1. 1. 1.]]
            1 on the border and 0 inside in the array
            [[ 0. 0. 0. 0. 0.]
            [ 0. 1. 1. 1. 0.]
            [ 0. 1. 1. 1. 0.]
            [ 0. 1. 1. 1. 0.]
            [ 0. 0. 0. 0. 0.]]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

arr = np.ones((3,3))
print("Orignal array\n", arr)


Orignal array
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
arr = np.pad(arr, pad_width = 1, mode= 'constant', constant_values = 0)
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
