In [12]:
'''
Title -  Write a Python program to how to add an extra column to an numpy array.
        Expected Output:
        [[ 10 20 30 100]
        [ 40 50 60 200]]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''


import numpy as np


array1 = np.array([[10,20,30], [40,50,60]])
array2 = np.array([[100], [200]])

print("Array1 : \n",array1,"\nArray2 : \n",array2)

Array1 : 
 [[10 20 30]
 [40 50 60]] 
Array2 : 
 [[100]
 [200]]


In [14]:
print(np.append(array2, array1, axis=1))

[[100  10  20  30]
 [200  40  50  60]]
