In [1]:
'''
Title -  Write a Python program to append values to the end of an array.
            Expected Output:
            Original array:
            [10, 20, 30]
            After append values to the end of the array:
            [10 20 30 40 50 60 70 80 90]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

ogArray = np.array([10,20,30])
print(ogArray)

[10 20 30]


In [3]:
# This is to add new Values to the Existing array.
updateArray = np.append(ogArray,[40,50,60,70,80,90], axis= None)
print(updateArray)

[10 20 30]
