In [11]:

'''
Title -  Create a 3x3 matrix with values ranging from 2 to 10.
        Expected Output:
        [[ 2 3 4]
        [ 5 6 7]
        [ 8 9 10]]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''
import numpy as np
arr = np.array([[2,3,4],[5,6,7],[8,9,10]] , ndmin =3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
print('number of dimensions :', arr.ndim)

number of dimensions : 2
