In [4]:
'''
Title - Write a Python program to convert a NumPy array into Python list structure.
        Expected Output:
        Original array elements:
        [[0 1]
        [2 3]
        [4 5]]
        Array to list:
        [[0, 1], [2, 3], [4, 5]]
Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

array1 = np.arange(9).reshape(3,3)
print("The orignal array format \n",array1)

The orignal array format 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(array1.tolist())