In [8]:

'''
Title -    Write a Python program to create a 2d array with 1 on the border and 0 inside.
            Expected Output:
            Original array:
            [[ 1. 1. 1. 1. 1.]
            [ 1. 1. 1. 1. 1.]
            [ 1. 1. 1. 1. 1.]
            [ 1. 1. 1. 1. 1.]
            [ 1. 1. 1. 1. 1.]]
            1 on the border and 0 inside in the array
            [[ 1. 1. 1. 1. 1.]
            [ 1. 0. 0. 0. 1.]
            [ 1. 0. 0. 0. 1.]
            [ 1. 0. 0. 0. 1.]
            [ 1. 1. 1. 1. 1.]]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎

'''

import numpy as np

arr = np.ones((5,5))
print("Orignal Array \n",arr)

Orignal Array 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
arr[1:-1,1:-1] = 0
print("Converted array\n", arr.nd)

Converted array
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
