In [9]:
'''
Title - Write a Python program to change the data type of an array.
        Expected Output:
        [[ 2 4 6]
        [ 6 8 10]]
        Data type of the array x is: int32
        New Type: float64
        [[ 2. 4. 6.]
        [ 6. 8. 10.]]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

array1 = np.array([[10,20,50],[80,70,60]], np.int32)
print(array1)
print("Data type of the array array1 is:",array1.dtype)

[[10 20 50]
 [80 70 60]]
Data type of the array array1 is: int32


In [10]:
array2 = array1.astype(float)
print(array2)
print("Data type of the array array2 is:",array1.dtype)

[[10. 20. 50.]
 [80. 70. 60.]]
