In [ ]:

'''
Title -   Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
            Checkerboard pattern:
            [[0 1 0 1 0 1 0 1]
            [1 0 1 0 1 0 1 0]
            [0 1 0 1 0 1 0 1]
            [1 0 1 0 1 0 1 0]
            [0 1 0 1 0 1 0 1]
            [1 0 1 0 1 0 1 0]
            [0 1 0 1 0 1 0 1]
            [1 0 1 0 1 0 1 0]]


Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎

'''

import numpy as np

arr = np.zeros((8,8))
print("Orignal Array of 8X8 matrix\n", arr)