In [12]:
'''
Title - Write a Python program to concatenate two 2-dimensional arrays.
        Expected Output:
        Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
        Expected Output:
        [[ 0 1 3 0 2 4]
        [ 5 7 9 6 8 10]]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

array1 = np.array([[0, 1, 3], [5, 7, 9]])

array2 = np.array([[0, 2, 4], [6, 8, 10]])


[[0 1 3]
 [5 7 9]] 
 [[ 0  2  4]
 [ 6  8 10]]


In [13]:
concat_array = np.concatenate((array1, array2), 1)

print(concat_array)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
