In [12]:
'''
Title - Write a Python program to create a contiguous flattened array.
        Original array:
        [[10 20 30]
        [20 40 50]]
        New flattened array:
        [10 20 30 20 40 50]
Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

array1 = np.array([[10 ,20 ,30],[20 ,40 ,50]])
print(array1)

[[10 20 30]
 [20 40 50]]


In [13]:
array2 = np.ravel(array1)
print("New flattened array:")
print(array2)

[10 20 30 20 40 50]
