In [8]:
'''
Title - Write a Python program to create an array which looks like below array.
        Expected Output:
        [[ 0. 0. 0.]
        [ 1. 0. 0.]
        [ 1. 1. 0.]
        [ 1. 1. 1.]]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

array1 = np.eye(3)
print(array1)



TypeError: eye() missing 1 required positional argument: 'N'