In [8]:
'''
Title - Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.
        Expected Output:
        [[ 1. 0. 0.]
        [ 0. 1. 0.]
        [ 0. 0. 1.]]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

array1 = np.eye(3)
print(array1)


NameError: name 'ndim' is not defined