In [16]:
'''
Title - Write a Python program to make an array immutable (read-only).
        Expected Output:
        Test the array is read-only or not:
        Try to change the value of the first element:
        Traceback (most recent call last):
        File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
        x[0] = 1
        ValueError: assignment destination is read-only

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

array1 = np.array([1,2,3,4,5])

print("The orignal array \n",array1)


The orignal array 
 [1 2 3 4 5]


In [17]:
array2 = np.append(array1, [6,7] )
print(array2)

[1 2 3 4 5 6 7]


In [18]:
array1.flags.writeable = False    
array1 = np.delete(-1)
print(array1)

[1 2 3 4 5 6 7 8]
