In [9]:

'''
Title -  Write a Python program to convert a list and tuple into arrays.
            List to array:
            [1 2 3 4 5 6 7 8]
            Tuple to array:
            [[8 4 6]
            [1 2 3]]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''
import numpy as np

list1 = list(input("Enter the comma seprated values of list : ").split(","))
print(list1)
tuple1 = ([8,4,6],[1,2,3])
print(tuple1)



['12', '87', '-45', '66', '1179', '23']
([8, 4, 6], [1, 2, 3])


In [10]:
arrayOfList = np.array(list1)
print(arrayOfList, type(arrayOfList))

['12' '87' '-45' '66' '1179' '23']


In [11]:
arrayOfTuple = np.array(tuple1)
print(arrayOfTuple, type(arrayOfTuple))

[[8 4 6]
 [1 2 3]]
