In [12]:
'''
Title - Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.
        Expected Output:
        Original array elements:
        [[ 0 1 2 3]
        [ 4 5 6 7]
        [ 8 9 10 11]]
        New array elements:
        [[ 0 3 6 9]
        [12 15 18 21]
        [24 27 30 33]]
Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

array1 = np.arange(12).reshape((3,4))
print(array1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
for units in np.nditer(array1, op_flags=['readwrite']):
    units[...] = 3 * units
print("New array elements:")
print(array1)

New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
