In [1]:

'''
Title -  Write a Python program to create a null vector of size 10 and update sixth value to 11.
        [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
        Update sixth value to 11
        [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎

'''
import numpy as np

var1 = np.zeros(10)
print(var1)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
print("Update sixth value to 11")
var1[6] = 11
print(var1)

Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
