In [2]:
'''
Title -  Write a Python program to remove specific elements in a numpy array.
        Expected Output:
        Original array:
        [ 10 20 30 40 50 60 70 80 90 100]
        Delete first, fourth and fifth elements:
        [ 20 30 60 70 80 90 100]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎
'''

import numpy as np

array1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(array1)

[ 10  20  30  40  50  60  70  80  90 100]


In [6]:
index = [0, 3, 4]
del_array = np.delete(array1 , index)
print(del_array)