In [9]:
'''
Title -    Write a Python program to find the set difference of two arrays. The set difference
            will return the sorted, unique values in array1 that are not in array2.
            Expected Output:
            Array1: [ 0 10 20 40 60 80]
            Array2: [10, 30, 40, 50, 70, 90]
            Set difference between two arrays:
            [ 0 20 60 80]

Author name - Aditya Kumar
Ceation time - ‎‎10 ‎March ‎2021 ‏‎
Modified time - ‎‎‎10 ‎March ‎2021‎

'''
import numpy as np

Array1 = np.array([ 0, 10, 20, 40, 60, 80])
Array2 = np.array([10, 30, 40, 50, 70, 90])

print("Array 1 : \n",Array1, "\nArray 2 :\n", Array2)

Array 1 : 
 [ 0 10 20 40 60 80] 
Array 2 :
 [10 30 40 50 70 90]


In [12]:
np.setdiff1d(Array1, Array2, assume_unique=False)

array([ 0, 20, 60, 80])