In [10]:
'''
Title - Write a Python program to suppresses the use of scientific notation for small
        numbers in numpy array.
        Expected Output:
        Original array elements:
        [ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
        Print array values with precision 3:
        [ 0. 1.6 1200. 0.235]

Author name - Aditya Kumar
Ceation time - ‎‎11 ‎March ‎2021 ‏‎
Modified time - ‎‎‎11 ‎March ‎2021‎

'''
import numpy as np

array1=np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
print("Original array elements:")
print(array1)


Original array elements:
[   0.       1.6   1200.       0.235]


In [9]:

print("Print array values with precision 3:")
np.set_printoptions(suppress=False)
print(x)

Print array values with precision 3:
[   0.       1.6   1200.       0.235]
